language: java
jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database todo;' -U postgres

cache:
  directories:
    - $HOME/.m2

# используем режим обычного пользователя для сборки проекта.
sudo: false

# Отправлять уведомление на почту youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -youcanwriteme@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
